name: Android Kernel Build
on:
  workflow_dispatch:

jobs:

  buildkernel:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      # Runs a single command using the runners shell
      - name: Build kernel 
        env:
           TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
           TELEGRAM_CHATID: ${{ secrets.TELEGRAM_CHATID }}
        run: bash build.sh

      - name: list fils
        run: |
         ls $(pwd)/arch/arm64/boot
      
      - name: Archive build output and send to tg
        run: |
          COMMIT_TITLE=$(echo "${{ github.event.head_commit.message }}" | head -n 1)
          echo "Commit Title: $COMMIT_TITLE"     
            mkdir -p output
          cp -r $(pwd)/arch/arm64/boot/* output/             
          sudo apt install curl
          curl -F "chat_id=1866453320" -F "document=@arch/arm64/boot/Image" "https://api.telegram.org/bot7854231397:AAHWtx4hS9ow-Lntr2-5TMJJq6KHSAxfd9o/sendDocument"
          curl -F "chat_id=1866453320" -F "document=@arch/arm64/boot/Image.gz" "https://api.telegram.org/bot7854231397:AAHWtx4hS9ow-Lntr2-5TMJJq6KHSAxfd9o/sendDocument"
          cp $(pwd)/arch/arm64/boot/Image $(pwd)/anykernel/
          cd anykernel; zip -9 -r ../output/a137f_u6_kernel_TESTING-$COMMIT_TITLE-$(date +%Y-%m-%d).zip ./* ; cd ..
          curl -F "chat_id=1866453320" -F "document=@output/a137f_u6_kernel_TESTING-$COMMIT_TITLE-$(date +%Y-%m-%d).zip" "https://api.telegram.org/bot7854231397:AAHWtx4hS9ow-Lntr2-5TMJJq6KHSAxfd9o/sendDocument"
          curl -F "chat_id=-1002124013929" -F "document=@output/a137f_u6_kernel_TESTING-$COMMIT_TITLE-$(date +%Y-%m-%d).zip"  -F caption="$COMMIT_TITLE" "https://api.telegram.org/bot7854231397:AAHWtx4hS9ow-Lntr2-5TMJJq6KHSAxfd9o/sendDocument"
          curl -F "chat_id=-1002150067042" -F "document=@output/a137f_u6_kernel_TESTING-$COMMIT_TITLE-$(date +%Y-%m-%d).zip"  -F caption="$COMMIT_TITLE" "https://api.telegram.org/bot7854231397:AAHWtx4hS9ow-Lntr2-5TMJJq6KHSAxfd9o/sendDocument"     
          curl -X POST "https://api.telegram.org/bot7854231397:AAHWtx4hS9ow-Lntr2-5TMJJq6KHSAxfd9o/sendMessage" -d "chat_id=2150067042" -d "text= $(date)  $COMMIT_TITLE"
          tar -czf release.tar.gz output
          cp release.tar.gz output/
          curl -F "chat_id=1866453320" -F "document=@output/release.tar.gz" "https://api.telegram.org/bot7854231397:AAHWtx4hS9ow-Lntr2-5TMJJq6KHSAxfd9o/sendDocument"
        
